### ISSUE TITLE
Cannot Install in MacOS Sierra - CLEAN FAILED - Using brew install carthage

### ISSUE THREAD

**Issue by tryjude** [Carthage/Carthage#1632]
Just wondering when Carthage will support Mac OS Sierra?

**Comment by af-fess** [comment]
I have the same issue:
```
$  brew install carthage --debug
/usr/local/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/carthage.rb
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/carthage.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/git.rb
==> Cloning https://github.com/Carthage/Carthage.git
Updating /Users/appsflyer/Library/Caches/Homebrew/carthage--git
==> Checking out tag 0.17.2
Synchronizing submodule url for 'Carthage/Checkouts/Curry'
Synchronizing submodule url for 'Carthage/Checkouts/Runes'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Supporting Files/Configuration'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/ReactiveCocoa'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Argo'
Synchronizing submodule url for 'Carthage/Checkouts/Curry'
Synchronizing submodule url for 'Carthage/Checkouts/OHHTTPStubs'
Synchronizing submodule url for 'Carthage/Checkouts/ReactiveCocoa'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/Curry'
Synchronizing submodule url for 'Carthage/Checkouts/Runes'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
==> make prefix_install PREFIX=/usr/local/Cellar/carthage/0.17.2
Last 15 lines from /Users/appsflyer/Library/Logs/Homebrew/carthage/01.make:
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
	Check dependencies
	Check dependencies
(3 failures)
make: *** [clean] Error 65
make: *** Waiting for unfinished jobs....
*** Bootstrapping Carthage/Checkouts/ReactiveCocoa...
*** Bootstrapping Carthage/Checkouts/ReactiveTask...
*** Bootstrapping Carthage/Checkouts/ReactiveCocoa...
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make prefix_install PREFIX=/usr/local/Cellar/carthage/0.17.2
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
==> Kept temporary files
Temporary files retained at /tmp/carthage-20161219-1715-m8ak5b

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```

I have last version Xcode: `Version 8.2 (8C38)`

**Comment by af-fess** [comment]
after opening Xcode I ran `$  brew install carthage --debug` again and got:

```
/usr/local/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/carthage.rb
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/carthage.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/git.rb
==> Cloning https://github.com/Carthage/Carthage.git
Updating /Users/appsflyer/Library/Caches/Homebrew/carthage--git
==> Checking out tag 0.17.2
Synchronizing submodule url for 'Carthage/Checkouts/Curry'
Synchronizing submodule url for 'Carthage/Checkouts/Runes'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Supporting Files/Configuration'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/ReactiveCocoa'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Argo'
Synchronizing submodule url for 'Carthage/Checkouts/Curry'
Synchronizing submodule url for 'Carthage/Checkouts/OHHTTPStubs'
Synchronizing submodule url for 'Carthage/Checkouts/ReactiveCocoa'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/Curry'
Synchronizing submodule url for 'Carthage/Checkouts/Runes'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
==> make prefix_install PREFIX=/usr/local/Cellar/carthage/0.17.2
Last 15 lines from /Users/appsflyer/Library/Logs/Homebrew/carthage/01.make:

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
	Check dependencies
	Check dependencies
(3 failures)
make: *** [clean] Error 65
make: *** Waiting for unfinished jobs....
*** Bootstrapping Carthage/Checkouts/Commandant...
*** Bootstrapping Carthage/Checkouts/ReactiveCocoa...
*** Bootstrapping Carthage/Checkouts/ReactiveTask...
*** Bootstrapping Carthage/Checkouts/ReactiveCocoa...
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make prefix_install PREFIX=/usr/local/Cellar/carthage/0.17.2
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 3
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
/usr/local/Library/Homebrew/formula.rb:1535:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1472:in `open'
/usr/local/Library/Homebrew/formula.rb:1472:in `system'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/carthage.rb:19:in `install'
/usr/local/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Library/Homebrew/debrew.rb:97:in `debrew'
/usr/local/Library/Homebrew/debrew.rb:22:in `install'
/usr/local/Library/Homebrew/build.rb:131:in `block in install'
/usr/local/Library/Homebrew/formula.rb:965:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1611:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:98:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:94:in `unpack'
/usr/local/Library/Homebrew/resource.rb:86:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb:171:in `stage'
/usr/local/Library/Homebrew/formula.rb:1599:in `stage'
/usr/local/Library/Homebrew/formula.rb:960:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'
```

**Comment by ikesyo** [comment]
@af-fess 

> /usr/local/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/carthage.rb
__Warning: You are using OS X 10.12.__
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/carthage.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/git.rb
==> Cloning https://github.com/Carthage/Carthage.git
Updating /Users/appsflyer/Library/Caches/Homebrew/carthage--git
__==> Checking out tag 0.17.2__

You are using an outdated version of homebrew. The latest version should already support Sierra and the latest Carthage version in homebrew is 0.18.1 (Carthage compiles with Xcode 8 from [0.18](https://github.com/Carthage/Carthage/releases/tag/0.18)). So you should update homebrew itself by `brew update`.
