### ISSUE TITLE
Carthage bootstrap fails with irrelevant git submodule error.

### ISSUE THREAD

**Issue by sleekweasel** [Carthage/Carthage#1641]
OBSERVED:

Appium invokes 'carthage bootstrap', which fails with a complaint about my top-level project not having the android_src submodule initialised - which is none of Carthage's business (especially when invoked from somewhere inside node_modules during an iOS build - the very reason we don't bother initialising the Android submodule!).

EXPECTED:

Carthage should complain only about its own directory structure.

WORKAROUND:

Running 'git init' somewhere between the directory in which carthage is invoked and the hosting project, so it stops looking for git stuff where it shouldn't be looking.

* `carthage version`: 0.18.1
* `xcodebuild -version`: Xcode 8.1 Build version 8B62
* Are you using `--no-build`? probably not.
* Are you using `--no-use-binaries`? probably not.
* Are you using `--use-submodules`? probably not.

**Cartfile**
```
# Used for HTTP routing
github "marekcirkos/RoutingHTTPServer"

# Used for USBOverHTTP
github "marekcirkos/peertalk"

# Used for XPath
github "marekcirkos/KissXML"
```

**Carthage Output**

Directly from the command-line:
```
$ carthage bootstrap
Parse error: expected submodule commit SHA in output of task (ls-tree -z HEAD build/sources/android_src) but encountered:
$ pwd
/Users/tim./git/booble/node_modules/appium-xcuitest-driver/WebDriverAgent
$ which carthage
/usr/local/bin/carthage
$ ls build/sources/android_src
ls: build/sources/android_src: No such file or directory
$ ls build
ls: build: No such file or directory
$ ls ~/git/booble/build/sources/
android_src      ios_src
```

From Appium's log:
```
2016-12-13 09:37:21:134 - info: [XCUITest] Using default agent: /Users/tim./git/booble/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
2016-12-13 09:37:21:134 - info: [XCUITest] Using default bootstrap: /Users/tim./git/booble/node_modules/appium-xcuitest-driver/WebDriverAgent
2016-12-13 09:37:21:135 - info: [XCUITest] Launching WebDriverAgent on the device
2016-12-13 09:37:21:271 - debug: [XCUITest] Carthage found: /usr/local/bin/carthage
2016-12-13 09:37:21:272 - debug: [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
2016-12-13 09:37:21:906 - error: [XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
 { Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  stdout: '\u001b[1mFetching dependencies\n*** Cloning KissXML\n',
  stderr: 'Parse error: expected submodule commit SHA in output of task (ls-tree -z HEAD build/sources/android_src) but encountered: \n',
  code: 1 }
2016-12-13 09:37:21:914 - error: [MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'command' of undefined
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/proxy-helper.js:13:35)
    at tryCatch (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.callee$0$0 [as proxyCommand] (../../../lib/commands/proxy-helper.js:13:10)
    at XCUITestDriver.stop$ (../../lib/driver.js:266:18)
    at tryCatch (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.stop (../../lib/driver.js:263:16)
    at XCUITestDriver.deleteSession$ (../../lib/driver.js:254:16)
    at tryCatch (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at XCUITestDriver.deleteSession (../../lib/driver.js:253:23)
    at XCUITestDriver.createSession$ (../../lib/driver.js:143:18)
    at tryCatch (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/tim./git/booble/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
2016-12-13 09:37:21:937 - info: [HTTP] <-- POST /wd/hub/session 500 29423 ms - 180
2016-12-13 09:37:37:777 - info: [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","deviceName":"iPhone 6","platformVersion":"10.1","app":"build/sources/ios_src/build/Build/Products/Calabash-iphonesimulator/Booble.app","autoAcceptAlerts":false,"automationName":"XCUITest","bundleId":"com.moomoo.booble","newCommandTimeout":305,"showIOSLog":false,"fullReset":true}}
2016-12-13 09:37:37:778 - debug: [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","deviceName":"iPhone 6","platformVersion":"10.1","app":"build/sources/ios_src/build/Build/Products/Calabash-iphonesimulator/Booble.app","autoAcceptAlerts":false,"automationName":"XCUITest","bundleId":"com.moomoo.booble","newCommandTimeout":305,"showIOSLog":false,"fullReset":true},null,null,null,null,null,null]
2016-12-13 09:37:37:779 - info: [Appium] Creating new XCUITestDriver session
```

**Comment by mdiep** [comment]
> Appium invokes 'carthage bootstrap', which fails with a complaint about my top-level project not having the android_src submodule initialised - which is none of Carthage's business (especially when invoked from somewhere inside node_modules during an iOS build - the very reason we don't bother initialising the Android submodule!).

Carthage is getting a list of submodules so it can avoid looking in those directories. That error comes from Git when Carthage asks for the submodules. It means that your submodule is configured improperly. You don't need to check out the submodule, but you can't have it half added. (It sounds like it's not included in `.gitmodules` like it should be.)

**Comment by sleekweasel** [comment]
$ git submodule foreach 'echo $name'
Entering 'build/sources/ios_src'
build/sources/ios_src

Not sure what you're doing to list submodules, but git doesn't seem to think Carthage should think there are any others.
