### ISSUE TITLE
brew reinstall fails - Can't install formulas

### ISSUE THREAD

**Issue by CorbinMontague** [Carthage/Carthage#3038]
* carthage install method: [ ] .pkg, [x] homebrew, [ ] source
* `which carthage`: /usr/local/bin/carthage
* `carthage version`: 0.35.0
* `xcodebuild -version`: Xcode 11.5 (11E608c)
* Are you using `--no-build`? No
* Are you using `--no-use-binaries`? No
* Are you using `--use-submodules`? No
* Are you using `--cache-builds`? Yes
* Are you using `--new-resolver`? No

**Cartfile**
```
# Platform
git "https://github.expedia.biz/vrbo-mobile-ios/comm-preferences.git" ~> 6.0
git "https://github.expedia.biz/vrbo-mobile-ios/picketline.git" ~> 29.0
git "https://github.expedia.biz/vrbo-mobile-ios/picketline-analytics.git" ~> 1.0
git "https://github.expedia.biz/vrbo-mobile-ios/uitoolkit.git" ~> 16.1.2

# Affirm
github "Affirm/affirm-merchant-sdk-ios" "5.0.10"

# DifferenceKit
github "ra1028/DifferenceKit" ~> 1.0

# Swinject (dependency injection)
github "Swinject/Swinject" ~> 2.0.0

# SKPhotoBrowser (image gallery)
github "suzuki-0000/SKPhotoBrowser" ~> 6.0.0

# Crashlytics
binary "https://building42.github.io/Specs/Carthage/iOS/Fabric.json" ~> 1.7.9
binary "https://building42.github.io/Specs/Carthage/iOS/Crashlytics.json" ~> 3.10.5

# Branch
github "BranchMetrics/ios-branch-deep-linking" "0.30.0"

# JLRoutes
# Point to master to fix the umbrella header warning.
github "joeldev/JLRoutes" "master"

# Segment
github "segmentio/analytics-ios" ~> 3.7.1

# SZTextView
github "glaszig/SZTextView" ~> 1.3.0

# JVFloatLabeledTextField
github "jverdi/JVFloatLabeledTextField" ~> 1.2.1

# GradientView
github "soffes/GradientView" ~> 2.3.3

# Cuckoo
github "SwiftKit/Cuckoo" "feature/tuist"

# Firebase
# https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md#carthage-usage
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 6.19.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json" == 6.19.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json" == 6.19.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseGoogleSignInBinary.json" == 6.19.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseRemoteConfigBinary.json" == 6.19.0

# Reachability
github "ashleymills/Reachability.swift" == 4.1

github "corban123/DateHelper" ~> 4.2.9

# Twilio
binary "https://raw.githubusercontent.com/twilio/twilio-accessmanager-ios/master/twilio-accessmanager-ios.json" ~> 1.0
binary "https://raw.githubusercontent.com/twilio/twilio-chat-ios/master/twilio-chat-ios.json" ~> 2.2

github "iziz/libPhoneNumber-iOS"

# Progress HUD
github "jdg/MBProgressHUD" ~> 1.1.0

github "SDWebImage/SDWebImage" ~> 5.5

github "michaeltyson/TPKeyboardAvoiding" ~> 1.3

github "Alamofire/Alamofire" ~> 4.7

github "ReactiveX/RxSwift" ~> 5.0
```

**Carthage Output**
```
$ brew "reinstall" "https://raw.githubusercontent.com/Homebrew/homebrew-core/27c7544d9bf5f9e4f09d7e47ba505f250b1259f2/Formula/carthage.rb"
Warning: Calling Installation of carthage from a GitHub commit URL is deprecated! Use 'brew extract carthage' to stable tap on GitHub instead.
Error: uninitialized constant Cask::CaskLoader::FromURILoader::Cache
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:101:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:206:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:206:in `block in for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:194:in `load'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:181:in `warn_if_cask_conflicts'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:62:in `block in to_resolved_formulae_to_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:59:in `each'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:59:in `to_resolved_formulae_to_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:64:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:113:in `<main>'
Can't install formulas:  exit status 1
```

**Actual outcome**
brew reinstall fails

**Expected outcome**
brew reinstall succeeds looking something like this:
```
$ brew "reinstall" "https://raw.githubusercontent.com/Homebrew/homebrew-core/27c7544d9bf5f9e4f09d7e47ba505f250b1259f2/Formula/carthage.rb"
Warning: Calling Installation of carthage from a GitHub commit URL is deprecated! Use 'brew extract carthage' to stable tap on GitHub instead.
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/27c7544d9bf5f9e4f09d7e47ba505f250b1259f2/Formula/carthage.rb.
==> Downloading https://homebrew.bintray.com/bottles/carthage-0.35.0.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/fdaacafff1566fa7b1e42e68e108da69aa7578dc82f4736272dca10283c9cba2?response-content-disposition=attachment%3Bfilename%3D%22carthage-0.35.0.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvZmRhYWNhZmZmMTU2NmZhN2IxZTQyZTY4ZTEwOGRhNjlhYTc1NzhkYzgyZjQ3MzYyNzJkY2ExMDI4M2M5Y2JhMj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmNhcnRoYWdlLTAuMzUuMC5jYXRhbGluYS5ib3R0bGUudGFyLmd6JTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTk4NjAyNTA3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=rWjVQzvjN8ndw2SWz8Kcy7Qa6sxjctus6lYSFPXXZixekN36aoM1OxwM2blvgP02do03O7OFDs6It4Do0Dh~k~FRetWye7OB3~gu2vkCzO9BzcWrtyu70dThCCGUErMwJRj1BsLf-QGKeXO6pkCxwwwkUEwGK3tpIYDFvd~r4SwLHLnh~xYQJERmpBrt5DwNzIEzfhVbkz45zU98CsVPQBGOT-hp-Y0wZEibrZ1NYeSkS9oJXb~HsjGZeTLIwHfbxx1sEd5ijocziPYhJv~h4SYxfd1WpXVSywDzOWo1bgKWSxRLZcFQzj~68Vs701IRYiFv1x5eSie-8Qw7oG~m3Q__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
==> Reinstalling carthage 
==> Pouring carthage-0.35.0.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/carthage/0.35.0: 8 files, 7.5MB
```

**Comment by tmspzz** [comment]
Not sure why this is. Does `uninstall` followed by `install` work?

**Comment by CorbinMontague** [comment]
@tmspzz Yes, a `brew uninstall carthage` followed by a `brew install carthage` does work. Is there something wrong with the formula that is causing the above failure?

**Comment by tmspzz** [comment]
Not that I can see atm.

**Comment by CorbinMontague** [comment]
I'll switch to using `install` instead of `reinstall`, but if this issue is being closed I guess it means you have no intention of continuing to support the ability to `reinstall` carthage using brew?

**Comment by tmspzz** [comment]
Maybe it's due to the `patch`, but since a workaround existing I don't think this is critical.
